-- Run this SQL in your Supabase SQL Editor to set up the necessary tables

-- 1. Create permissions Enum
CREATE TYPE user_role AS ENUM ('lector', 'coordinador', 'administrador');

-- 2. Create Profiles table
CREATE TABLE IF NOT EXISTS profiles (
  id uuid REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  email text,
  role user_role DEFAULT 'lector',
  initials text,
  full_name text,
  created_at timestamptz DEFAULT now()
);

-- 3. Enable RLS on profiles
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- 4. Create Audit Logs table
CREATE TABLE IF NOT EXISTS audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  user_id uuid REFERENCES auth.users,
  case_id text,
  action text,
  details jsonb,
  changes jsonb
);

-- 5. Enable RLS on audit_logs
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;

-- 6. RLS Policies

-- Profiles:
-- Everyone can read
CREATE POLICY "Profiles viewable by authenticated users" ON profiles FOR SELECT TO authenticated USING (true);
-- Only admins can update role
CREATE POLICY "Profiles updatable by admins" ON profiles FOR UPDATE TO authenticated USING (
  exists (select 1 from profiles where id = auth.uid() and role = 'administrador')
);
-- Users can update their own initials/name
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE TO authenticated USING (auth.uid() = id);
-- Trigger to create profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, role, initials, full_name)
  VALUES (
    new.id, 
    new.email, 
    'lector', 
    upper(substring(new.email from 1 for 2)), 
    new.raw_user_meta_data->>'full_name'
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Audit Logs:
-- Viewable by everyone (or restrict to coordinators+)
CREATE POLICY "Audit logs viewable by authenticated users" ON audit_logs FOR SELECT TO authenticated USING (true);
-- Insertable by everyone
CREATE POLICY "Audit logs insertable by authenticated users" ON audit_logs FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
